# Compilation

FROM maven:3.6.3-openjdk-17 as builder

WORKDIR /project

# Copy of project dependencies
COPY pom.xml /project/

# Error
# RUN mvn clean verify -e -X

# Source code copy to /src
COPY /src /project/src

# Compile project
RUN mvn package

# Application container

FROM openjdk:17

WORKDIR /usr/src/app/

# Copy JAR from /project/target/ to /usr/src/app/
COPY --from=builder /project/target/*.jar /usr/src/app/

# Port 8443
EXPOSE 8443

# Parameter
CMD [ "java", "-jar", "webapp3-0.0.1-SNAPSHOT.jar" ]